# Generated by Django 5.2.1 on 2025-06-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250605_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='theory_questions',
        ),
    ]
