# Generated by Django 5.2 on 2025-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectstep'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectstep',
            name='code_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectstep',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectstep',
            name='code_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectstep',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='projectstep',
            name='timestamp',
        ),
    ]
