# Generated by Django 5.2 on 2025-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='description',
            new_name='step_description',
        ),
        migrations.RemoveField(
            model_name='step',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='step',
            name='title',
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='week',
            field=models.IntegerField(),
        ),
    ]
