# Generated by Django 5.2 on 2025-06-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_description_step_step_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
