# Generated by Django 5.2 on 2025-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_resume_text_userprofile_skill_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill_assessment',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(default=1, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(to='core.skill'),
        ),
    ]
