# Generated by Django 5.2 on 2025-06-14 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_userprofile_resume_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CHALLENGE_COMPLETE', 'Challenge Completed'), ('PROJECT_START', 'Project Started'), ('SKILL_IMPROVE', 'Skill Improved'), ('PROJECT_UPDATE', 'Project Updated'), ('RESUME_UPLOAD', 'Resume Uploaded'), ('RESUME_UPLOAD_ATTEMPT', 'Duplicate Resume Attempt'), ('RESUME_UPLOAD_ERROR', 'Resume Upload Error'), ('RESUME_ANALYSIS', 'Resume Analyzed'), ('CHALLENGES_GENERATED', 'Challenges Generated'), ('NO_CHALLENGES', 'No Challenges Generated'), ('CHALLENGE_GENERATION_ERROR', 'Challenge Generation Error')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
