# Generated by Django 5.2.4 on 2025-07-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
